[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "callpy"
dynamic = ["version"]
description = "Multi protocol, auto-cluster server framework."
readme = "README.md"
requires-python = ">=3.6"
license = {text = "MIT"}
authors = [
    {name = "Wei Zhuo", email = "zeaphoo@qq.com"}
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Web Environment",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Topic :: Internet :: WWW/HTTP",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: Implementation :: CPython"
]
dependencies = [
    "websockets>=9.0",
    "httptools>=0.4.0",
    "basepy>=0.3.1",
    "aiofiles",
    "setproctitle",
    "uvloop>=0.14.0;sys_platform!='win32'"
]

[project.scripts]
callpy-manager = "callpy.manager:run_manager"

[tool.hatch.build.targets.wheel]
packages = ["callpy"]

[tool.hatch.version]
path = "callpy/__init__.py"


