
[log]
    handlers = ["stdout"]

    [log.stdout]
    handler_type = "stdout"
    level = "debug"

[editor]
    port = 9080
    server_url = 'http://127.0.0.1:5000'
    editor_url = 'http://127.0.0.1:8000/editor'

[[editor.servers]]
    name = "Server Name"
    description = "Building/Debug Server"
    server_url = 'http://127.0.0.1:5000'
    client_key = 'xxx'
    client_secret = ''


[server]
    debug = true
    port = 9000
    db_url = 'postgres://postgres:postgres@127.0.0.1:5432/highorder?min_size=10&max_size=30'
    config_dir = './working_dir/building'
    content_location = './working_dir/building'
    content_url = ''
    webapp_root = '../webapp/dist/'
    redis_urls = [ "redis://127.0.0.1:6379" ]

[[server.setup_keys]]
    client_key = 'console_client_key'
    client_secret = 'console_client_secret'